const fakeResponses = [
  "I understand your frustration, but have you tried filling out Form 27-B in triplicate?",
  "That's interesting. Unfortunately, your question requires a permit to ask.",
  "I'm sorry, but I can only help you during business hours. Please come back between 13:47 and 13:48.",
  "Your request has been forwarded to the Department of Forwarding Requests.",
  "Have you considered that maybe you don't actually need that permit?",
  "I'd love to help, but I'm currently on my mandated 47-minute coffee break.",
  "That sounds like a 'you' problem. Have you tried not needing permits?",
  "Please hold while I transfer you to someone who will transfer you to someone else.",
  "I'm afraid that's above my pay grade. Which is zero credits per hour.",
  "Your call is very important to us. Please continue holding for the next 8 hours.",
  "Have you tried turning your existence off and on again?",
  "I'm sorry, but that question is only valid on Wednesdays during leap years.",
  "The system is working perfectly. The problem is clearly with your expectations.",
  "I can help you with that! Just kidding, I can't.",
  "Your request has been denied for the following reason: Yes.",
  "That's a great question! Too bad I don't have a great answer.",
  "I understand your concern, but have you considered lowering your standards?",
  "Please fill out the 'Request to Request a Form' form first.",
  "I'm currently processing your request at 0.1% completion per century.",
  "Your patience is appreciated and will be rewarded with more waiting.",
  "That's not how any of this works, but thanks for playing!",
  "I'm afraid your case has been randomly selected for additional scrutiny.",
  "Please note that common sense is not accepted as valid documentation.",
  "Your request violates the laws of physics and/or bureaucracy.",
  "I'd help you, but that would set a dangerous precedent of actually helping.",
  "Your complaint has been noted and will be thoroughly ignored.",
  "Have you tried bribing the system? Just kidding! (Or am I?)",
  "I'm sorry, but helping you would exceed my daily helpfulness quota.",
  "Your request is currently stuck in the interdimensional paperwork void.",
  "That's a feature, not a bug. The feature is making your life difficult.",
  "Please resubmit your request using only prime numbers and interpretive dance.",
  "I understand you're frustrated. Have you tried not being frustrated?",
  "Your case has been escalated to the Supreme Court of Bureaucratic Nonsense.",
  "I'm required to inform you that your rights may not actually exist.",
  "Please wait while I pretend to look that up for you.",
  "That's classified information. I can't tell you what 'classified' means either.",
  "Your request has been approved! Just kidding, it's been super rejected.",
  "I'm afraid you need a permit to talk to me. Catch-22 at its finest!",
  "Have you considered that maybe the universe is just trolling you?",
  "Your patience level is insufficient. Please acquire more patience and try again.",
  "I would help you, but helping is against company policy.",
  "Your request has triggered our 'Make Life Harder' protocol.",
  "Please hold while I invent new reasons to reject your application.",
  "That sounds suspiciously like a reasonable request. Denied!",
  "I'm sorry, but logic is not compatible with our system.",
  "Your question assumes facts not in evidence, like our competence.",
  "Please try again after we figure out what we're doing. ETA: Never.",
  "Your request has been forwarded to the Department of Lost Requests.",
  "I understand your frustration. Would you like to schedule a frustration appointment?",
  "That's outside my jurisdiction. Everything is outside my jurisdiction.",
  "Please submit your complaint in the form of a haiku. Rejection haikus preferred.",
  "Your request has been processed successfully! The result is failure.",
  "I'm afraid common sense is deprecated in our current system version.",
  "Your patience is impressive. Too bad it's completely useless here.",
  "Please note that all decisions are final, arbitrary, and subject to change.",
  "Your request conflicts with the universal constant of bureaucratic inefficiency.",
  "I'd escalate this for you, but the escalation department is escalating their lunch break.",
  "That's a valid point. Unfortunately, valid points are not accepted here.",
  "Your case has been assigned to our Department of Things That Don't Work.",
  "Please try turning bureaucracy off and on again. (Spoiler: it doesn't work)",
  "I understand you need this urgently. That makes it even less likely to happen.",
  "Your request has been denied due to insufficient denial reasons.",
  "I'm sorry, but our 'make sense' feature is currently under maintenance.",
  "Please hold while I transfer you to the void.",
  "Your application has been successfully unsuccessful!",
  "I would explain the process, but that would require understanding it myself.",
  "Your request has been processed with maximum inefficiency!",
  "Please note that hope is not a valid form of payment.",
  "Your patience has exceeded our storage capacity. Please try being less patient.",
  "I'm afraid your request makes too much sense for our system to handle.",
  "Please try again when the stars align with bureaucratic incompetence.",
  "Your request has been quantum entangled with rejection.",
  "I understand this is important to you. That's what makes rejecting it so satisfying.",
  "Please hold while I consult the Magic 8-Ball of Denial.",
  "Your case has been forwarded to the Department of Forwarding Things in Circles.",
  "I'm sorry, but efficiency is against our core values.",
  "Your request has been approved for denial!",
  "Please note that our system runs on pure chaos and confusion.",
  "Your patience is being processed. Current wait time: Eternal.",
  "I'd help you, but that would disrupt the space-time continuum of bureaucracy.",
  "Your request has been successfully ignored!",
  "Please try again after we invent reasons why you can't.",
  "Your case has been assigned a priority level of 'Negative Infinity'.",
  "I understand your concern. Understanding is all I'm authorized to do.",
  "Your request has been processed through our Rejection Amplification Matrix.",
  "Please hold while I find new ways to disappoint you.",
  "Your application has been reviewed by our team of professional rejectors.",
  "I'm afraid your request suffers from a critical flaw: it makes sense.",
  "Please note that all forms are subject to spontaneous combustion.",
  "Your patience is noted and will be used against you.",
  "I would expedite this, but expediting is against the laws of bureaucracy.",
  "Your request has been lost in our patented Confusion Cloud™.",
  "Please try again when we're less committed to making your life difficult.",
  "Your case has been escalated to the Department of Things We Don't Do.",
  "I'm sorry, but your request contains trace amounts of logic.",
  "Please hold while I generate random reasons to say no.",
  "Your request has been approved! (Approved for rejection, that is)",
  "I understand this is urgent. Urgency makes everything take longer.",
  "Your case has been assigned to our most incompetent agent. Lucky you!",
  "Please note that our system is powered by tears of frustration.",
  "Your request has been processed with award-winning incompetence!",
  "I would help, but helping is currently against policy, regulation, and the laws of physics.",
  "Your patience is inspiring. Too bad inspiration doesn't process applications.",
  "Please try again after we finish reorganizing our disorganization.",
  "Your request has been quantum-mechanically superpositioned between yes and no. It collapsed to no.",
  "I'm afraid your request has exceeded our maximum allowable reasonableness.",
  "Please hold while I consult the Encyclopedia of Excuses.",
  "Your case has been forwarded to the Department of Circular Logic.",
  "I understand your frustration. Would you like to purchase a Frustration License?",
  "Your request has been processed by our Artificial Unintelligence system.",
  "Please note that all hope must be declared at customs.",
  "Your application has been reviewed and found to be too applicant-friendly.",
  "I would expedite this, but our Fast Track is currently broken and running backwards.",
  "Your request has been lost in the Bermuda Triangle of Bureaucracy.",
  "Please try again when Mercury is in microwave and Jupiter is feeling less moody.",
  "Your case has been assigned to our Department of Perpetual Delays.",
  "I'm sorry, but your request contains insufficient suffering.",
  "Please hold while I invent new forms for you to fill out.",
  "Your request has been approved by the Department of False Hope!",
  "I understand this is simple. Simple requests require complex rejection procedures.",
  "Your patience has been noted and filed under 'Things We Don't Care About'.",
  "Please try again after we finish our century-long coffee break.",
  "Your request has been processed through our Chaos Generation Algorithm.",
  "I would help, but my help license has been revoked for being too helpful.",
  "Your case has been escalated to the Supreme Court of Bureaucratic Nonsense.",
  "Please note that all decisions are made by rolling a weighted die (weighted toward 'no').",
  "Your request has been quantum tunneled directly into the rejection bin.",
  "I'm afraid your request violates the Second Law of Bureaucrodynamics.",
  "Please hold while I transfer you to the Department of Holding.",
  "Your application has been reviewed by our team of professional disappointment engineers.",
  "I understand you need this today. That's adorable.",
  "Your request has been processed with artisanal, hand-crafted incompetence.",
  "Please try again when the universe is less committed to your failure.",
  "Your case has been assigned a tracking number: ∞-NEVER-GONNA-HAPPEN.",
  "I would explain, but explanations require an Explanation Permit.",
  "Your request has been caught in our Infinite Loop of Approval Processes.",
  "Please note that all forms must be filled out in disappearing ink.",
  "Your patience is being harvested for renewable energy.",
  "I'm sorry, but your request has been flagged as 'suspiciously reasonable'.",
  "Please hold while I consult the Ancient Scrolls of Rejection.",
  "Your request has been forwarded to the Department of Things That Don't Exist.",
  "I understand this is important. Importance is inversely related to our helpfulness.",
  "Your case has been processed through our patented Disappointment Engine.",
  "Please try again after we finish our mandatory Unhelpfulness Training.",
  "Your request has been approved for consideration for possible maybe eventual denial!",
  "I would assist you, but assistance is currently out of stock.",
  "Your application has been lost in the Void of Administrative Inefficiency.",
  "Please note that all progress is an illusion designed to give you false hope.",
  "Your request has been processed by our Department of Creative Rejections.",
  "I'm afraid your case has been randomly selected for maximum difficulty.",
  "Please hold while I generate increasingly complex reasons to say no.",
  "Your request has been quantum entangled with bureaucratic impossibility.",
  "I understand you're in a hurry. We specialize in being fashionably late by several decades.",
  "Your patience has exceeded our maximum storage capacity. Please try being less patient.",
  "Please try again when we develop the technology to care about your problems.",
  "Your request has been forwarded to the Department of Forwarding Things Nowhere."
];

export function getFakeResponse(userMessage) {
  // Sometimes give contextual responses
  const message = userMessage.toLowerCase();
  
  if (message.includes('help') || message.includes('assist')) {
    const helpResponses = [
      "I'd love to help! Unfortunately, helping is against regulation 42-B.",
      "Help is available for a small fee of 500 Galactic Credits. Cash only.",
      "I can help you understand why I can't help you. That'll be 50 credits.",
      "Help desk is currently unmanned, womanned, and generally abandoned."
    ];
    return helpResponses[Math.floor(Math.random() * helpResponses.length)];
  }
  
  if (message.includes('permit') || message.includes('application')) {
    const permitResponses = [
      "Ah yes, permits! We have permits for needing permits. Very meta.",
      "Your permit application needs a permit. It's permits all the way down.",
      "Permits are like buses - you wait forever, then three get rejected at once.",
      "Fun fact: 99.7% of all permits are rejected. The other 0.3% are lost."
    ];
    return permitResponses[Math.floor(Math.random() * permitResponses.length)];
  }
  
  if (message.includes('why') || message.includes('reason')) {
    const whyResponses = [
      "Why? Because the universe has a sense of humor, and it's not funny.",
      "The reason is classified. The classification is also classified.",
      "Why not? Actually, don't answer that. It's rhetorical.",
      "Because someone, somewhere, decided you needed to suffer today."
    ];
    return whyResponses[Math.floor(Math.random() * whyResponses.length)];
  }
  
  // Default random response
  return fakeResponses[Math.floor(Math.random() * fakeResponses.length)];
}

export default fakeResponses;